### ISSUE TITLE
Not compatible with OwnCloud 10.11.0

### ISSUE THREAD

**Issue by josemaX** [westberliner/checksum#67]
Hello

Just updated to OC 10.10 -> 10.11.0 and had to disable checksum to complete upgrade because not compatible (perhaps only version check?).

Best,

**Comment by nathanielhourt** [comment]
Yep, I just tried installing it and was briefly foiled by the same. I think it's just an outdated version check, though, because I went and edited the app's `appinfo/info.xml` file on disk to allow v10.11, and it seems to be working just fine.

A bit disconcerting that the code signature check didn't throw on that one... but it works.

**Comment by westberliner** [comment]
Hi,

I tried to install it with the current release and failed.

```
Message: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found
```

But the 0.3.5 Version still works. I'll try to create a release. Have to figure out a suitable way to maintain the OC releases.

**Comment by westberliner** [comment]
I'll created a 0.3.6 release and pushed it into the marketplace.
